/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FifoPipeOutputStream */

#ifndef _Included_FifoPipeOutputStream
#define _Included_FifoPipeOutputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FifoPipeOutputStream
 * Method:    unlinkPipeName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_FifoPipeOutputStream_unlinkPipeName
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
