/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class spartan_LaunchProgram */

#ifndef _Included_spartan_LaunchProgram
#define _Included_spartan_LaunchProgram
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     spartan_LaunchProgram
 * Method:    log
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_spartan_LaunchProgram_log
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     spartan_LaunchProgram
 * Method:    invokeProgramCommand
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)Lspartan/Spartan/InvokeResponse;
 */
JNIEXPORT jobject JNICALL Java_spartan_LaunchProgram_invokeProgramCommand
  (JNIEnv *, jclass, jstring, jobjectArray);

/*
 * Class:     spartan_LaunchProgram
 * Method:    invokeCommand
 * Signature: ([Ljava/lang/String;)Lspartan/Spartan/InvokeResponse;
 */
JNIEXPORT jobject JNICALL Java_spartan_LaunchProgram_invokeCommand
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     spartan_LaunchProgram
 * Method:    killSIGINT
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_spartan_LaunchProgram_killSIGINT
  (JNIEnv *, jclass, jint);

/*
 * Class:     spartan_LaunchProgram
 * Method:    killSIGKILL
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_spartan_LaunchProgram_killSIGKILL
  (JNIEnv *, jclass, jint);

/*
 * Class:     spartan_LaunchProgram
 * Method:    killProcessGroupSIGINT
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_spartan_LaunchProgram_killProcessGroupSIGINT
  (JNIEnv *, jclass, jint);

/*
 * Class:     spartan_LaunchProgram
 * Method:    killProcessGroupSIGKILL
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_spartan_LaunchProgram_killProcessGroupSIGKILL
  (JNIEnv *, jclass, jint);

/*
 * Class:     spartan_LaunchProgram
 * Method:    getSysThreadID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_spartan_LaunchProgram_getSysThreadID
  (JNIEnv *, jclass);

/*
 * Class:     spartan_LaunchProgram
 * Method:    sysThreadInterrupt
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_spartan_LaunchProgram_sysThreadInterrupt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     spartan_LaunchProgram
 * Method:    isFirstInstance
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_spartan_LaunchProgram_isFirstInstance
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
